#! /usr/bin/env python
from __future__ import print_function

import sys

try:
    import ROOT
    root_version = ROOT.__version__
except ImportError:
    root_version = 'Not available'

try:
    import tensorflow as tf
    tf_version = tf.__version__
except ImportError:
    tf_version = 'Not available'

print ( 'Python     : ', sys.version.split()[0] )
print ( 'ROOT       : ', root_version )
print ( 'Tensorflow : ', tf_version )
